---
title: "Kai's Covid-19 Dashboard"
runtime: shiny
output: html_document
---
A look at a few interesting data points related to Covid-19 pandemic. This is data covering all of 2020 up to May 14-17 (14th for Republic of Korea data, 17 for the United States)


```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(dplyr)
library(lubridate)
library(zoo)
source('functions.R')
```

```{r, echo = FALSE}
#define the function
fun1 <- function(x){ (x - lag(x))/lag(x)}
```

```{r, echo=FALSE}
korea_cases <- read_csv('data/korea_dataset/Time.csv')
korea_cases <- korea_cases %>% 
  mutate(positiveIncrease = confirmed - lag(confirmed, default = confirmed[1]))
korea_cases <- korea_cases %>% 
  mutate(deathIncrease = deceased - lag(deceased, default = deceased[1]))
korea_cases <- korea_cases %>% 
  mutate(testIncrease = test - lag(test, default = test[1]))

us_cases <- read_csv('data/us_dataset/us_covid19_daily.csv')
us_cases$date <- parse_date_time(us_cases$date, orders = "ymd")

us_state_cases <- read_csv('data/us_dataset/us_states_covid19_daily.csv')
us_state_cases$date <- parse_date_time(us_state_cases$date, orders = "ymd")

```


### Korea

```{r}
ggplot(data = korea_cases, aes(x = date, y = positiveIncrease)) +
  geom_bar(stat="identity", fill="orange", color="black") +
  geom_line(aes(y=rollmean(positiveIncrease, 7, na.pad=TRUE)), 
            color="dodgerblue", size=2) +
  labs(title="Korea: New Detected Cases",
       x="Date",
       y="New Cases")
```

```{r}
ggplot(data = korea_cases, aes(x = date, y = deathIncrease)) +
  geom_bar(stat="identity", fill="purple", color="black") +
  geom_line(aes(y=rollmean(deathIncrease, 7, na.pad=TRUE)),
            color="black", size=2) +
  labs(title="Korea: Deaths",
       x="Date",
       y="New Deaths")
```




### United States

```{r}
ggplot(data = us_cases, aes(x = date, y = positiveIncrease)) +
  geom_bar(stat="identity", fill="orange", color="black") +
  geom_line(aes(y=rollmean(positiveIncrease, 7, na.pad=TRUE)), 
            color="dodgerblue", size=2) +
  labs(title="US: New Detected Cases",
       x="Date",
       y="New Cases")
```

```{r}
ggplot(data = us_cases, aes(x = date, y = deathIncrease)) +
  geom_bar(stat="identity", fill="purple", color="black") +
  geom_line(aes(y=rollmean(deathIncrease, 7, na.pad=TRUE)),
            color="black", size=2) +
  labs(title="US: Deaths",
       x="Date",
       y="New Deaths")
```



### US States

```{r, echo=FALSE}
inputPanel(
  selectInput("state", label = "State",
              choices = us_state_cases$state,
              selected = "CA")
)

renderPlot({
  ggplot(us_state_cases[us_state_cases$state == input$state,], 
         aes(x = date, y = positiveIncrease)) +
    geom_bar(stat="identity") +
    geom_line(aes(y=rollmean(positiveIncrease, 7, na.pad=TRUE)), color="black")
})

renderPlot({
    ggplot(us_state_cases[us_state_cases$state == input$state,], 
           aes(x = date, y = deathIncrease, fill)) +
    geom_bar(stat="identity", color="black", fill="red") +
    geom_line(aes(y=rollmean(deathIncrease, 7, na.pad=TRUE)), color="black",
              size=2)
})

renderPlot({
  ggplot(data = us_state_cases[us_state_cases$state == input$state,], 
         aes(x = totalTestResultsIncrease, y = positiveIncrease)) +
    geom_point() +
    geom_smooth(method="lm")
})

```

### How Correlated are New Tests with Case?

### Korea

```{r}
ggplot(data = korea_cases, aes(x = testIncrease, y = positiveIncrease)) +
  geom_point() +
  geom_smooth(method="lm")
```

### US

```{r}
ggplot(data = us_cases, aes(x = totalTestResultsIncrease, y = positiveIncrease)) +
  geom_point() +
  geom_smooth(method="lm")
```
